from friday.llm.local_llm import generate_response

def generate_code(task: str) -> str:
    \"\"\"Generate clean Python code for the task using local LLM.\"\"\"
    prompt = "Write a clean, complete, runnable Python program for this task: " + task + "\n\nRequirements:\n- Complete code only (no explanations or markdown)\n- Add shebang if needed\n- Use best practices\n- Make it self-contained\n\nOutput ONLY the Python code, no other text."
    code = generate_response(prompt)
    
    # Clean code (remove markdown if any)
    lines = code.split('\n')
    code = '\n'.join(line for line in lines if not line.strip().startswith('```'))
    
    if '```python' in code:
        start = code.find('```python') + 9
        end = code.find('```', start)
        if end > start:
            code = code[start:end].strip()
    
    code = code.strip()
    
    if not code.startswith('#!') and not code.startswith('import ') and 'def ' not in code[:100]:
        code = "# Generated by FRIDAY\n" + code
    
    return code

